// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunBundledInstaller() {
  return window['go']['installer']['Installer']['RunBundledInstaller']();
}

export function RunInstalledApp() {
  return window['go']['installer']['Installer']['RunInstalledApp']();
}

export function Startup(arg1) {
  return window['go']['installer']['Installer']['Startup'](arg1);
}
